export const euFlagPlaceholder =
  "https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg";

export const languagesOptions = [
  "TOP 13 LANGUAGES",
  { top: true, flag: "us", value: "English (USA)" },
  { top: true, flag: "gb", value: "English (UK)" },
  { top: true, flag: "de", value: "German" },
  { top: true, flag: "fr", value: "French" },
  { top: true, flag: "ru", value: "Russian" },
  { top: true, flag: "es", value: "Spanish" },
  { top: true, flag: "es", value: "Spanish (Latin-America)" },
  { top: true, flag: "it", value: "Italian" },
  { top: true, flag: "pt", value: "Portuguese (Brazil)" },
  { top: true, flag: "hk", value: "Simplified Chinese (Mainland China)" },
  { top: true, flag: "ae", value: "Arabic" },
  { top: true, flag: "jp", value: "Japanese" },
  { top: true, flag: "nl", value: "Dutch" },
  { top: true, flag: "gr", value: "Greek" },
  { top: true, flag: "ro", value: "Romanian" },
  "OTHER LANGUAGES",
  { flag: "af", value: "Afrikaans" },
  { flag: "al", value: "Albanian" },
  { flag: "am", value: "Amharic" },
  {
    flag: "ae",
    value: "Arabic",
    subs: [
      { flag: "ae", value: "Arabic -> (Formal)" },
      { flag: "ae", value: "Arabic -> (Egyptian)" },
      { flag: "ae", value: "Arabic -> (Gulf)" },
      { flag: "ae", value: "Arabic -> (Levantine)" },
      { flag: "ae", value: "Arabic -> (Maghrebi)" },
    ],
  },
  { flag: "am", value: "Armenian" },
  { flag: "as", value: "Assamese" },
  { flag: "az", value: "Azerbaijani" },
  { flag: "eu", value: "Basque" },
  { flag: "by", value: "Belarussian" },
  { flag: "bn", value: "Bengali" },
  { flag: "ba", value: "Bosnian" },
  { flag: "bg", value: "Bulgarian" },
  { flag: "my", value: "Burmese" },
  { flag: "ad", value: "Catalan" },
  {
    flag: "hk",
    value: "Chinese",
    subs: [
      { flag: "hk", value: "Chinese -> Simplified Chinese (Mainland China)" },
      { flag: "hk", value: "Chinese -> (Mainland China)" },
      { flag: "hk", value: "Chinese -> (Traditional - Taiwan)" },
      { flag: "hk", value: "Chinese -> (Traditional - Hong Kong)" },
      { flag: "hk", value: "Chinese -> (Traditional - Cantonese)" },
      { flag: "hk", value: "Chinese -> (Shanghainese)" },
    ],
  },
  { flag: "hr", value: "Croatian" },
  { flag: "cz", value: "Czech" },
  { flag: "dk", value: "Danish" },
  { flag: "af", value: "Dari" },
  { flag: "nl", value: "Dutch" },
  { flag: "us", value: "English (USA)" },
  { flag: "gb", value: "English (UK)" },
  { flag: "ee", value: "Estonian" },
  { flag: "fi", value: "Finnish" },
  { flag: "be", value: "Flemish (Belgian)" },
  {
    flag: "fr",
    value: "French",
    subs: [
      { flag: "fr", value: "French -> (France)" },
      { flag: "fr", value: "French -> (Canada)" },
      { flag: "fr", value: "French -> (Swiss)" },
    ],
  },
  { flag: "gl", value: "Galician" },
  { flag: "ge", value: "Georgian" },
  {
    flag: "de",
    value: "German",
    subs: [{ flag: "de", value: "German -> (Swiss)" }],
  },
  { flag: "gr", value: "Greek" },
  { flag: "gu", value: "Gujarati" },
  { flag: "ht", value: "Haitian Creole" },
  { flag: "ne", value: "Hausa" },
  { flag: "il", value: "Hebrew" },
  { flag: "in", value: "Hindi" },
  { flag: "hu", value: "Hungarian" },
  { flag: "is", value: "Icelandic" },
  { flag: "ie", value: "Irish Gaelic" },
  { flag: "id", value: "Indonesian" },
  { flag: "it", value: "Italian" },
  { flag: "jp", value: "Japanese" },
  { flag: "kn", value: "Kannada" },
  { flag: "kz", value: "Kazakh" },
  { flag: "km", value: "Khmer" },
  { flag: "kr", value: "Korean" },
  { flag: "tr", value: "Kurdish" },
  { flag: "la", value: "Lao" },
  { flag: "lv", value: "Latvian" },
  { flag: "lt", value: "Lithuanian" },
  { flag: "mk", value: "Macedonian" },
  { flag: "ms", value: "Malay" },
  { flag: "ml", value: "Malayalam" },
  { flag: "mt", value: "Maltese" },
  { flag: "mr", value: "Marathi" },
  { flag: "mn", value: "Mongolian" },
  { flag: "me", value: "Montenegrin" },
  { flag: "ne", value: "Nepali" },
  { flag: "no", value: "Norwegian" },
  { flag: "pk", value: "Pashto" },
  { flag: "ir", value: "Persian" },
  { flag: "pl", value: "Polish" },
  {
    flag: "pt",
    value: "Portuguese",
    subs: [
      { flag: "pt", value: "Portuguese -> (Brazil)" },
      { flag: "pt", value: "Portuguese -> (Portugal)" },
    ],
  },
  { flag: "pa", value: "Punjabi" },
  { flag: "ro", value: "Romanian" },
  { flag: "ru", value: "Russian" },
  { flag: "rs", value: "Serbian (Cyrillic)" },
  { flag: "rs", value: "Serbian (Latin)" },
  { flag: "si", value: "Sinhala" },
  { flag: "sl", value: "Slovak" },
  { flag: "sl", value: "Slovenian (Slovene)" },
  { flag: "so", value: "Somali" },
  {
    flag: "es",
    value: "Spanish",
    subs: [
      { flag: "es", value: "Spanish -> (Mexico)" },
      { flag: "es", value: "Spanish -> (Spain)" },
      { flag: "es", value: "Spanish -> (Latin America)" },
    ],
  },
  { flag: "ke", value: "Swahili" },
  { flag: "se", value: "Swedish" },
  { flag: "ch", value: "Swiss" },
  { flag: "tl", value: "Tagalog" },
  { flag: "tg", value: "Tajik" },
  { flag: "lk", value: "Tamil" },
  { flag: "in", value: "Telugu" },
  { flag: "th", value: "Thai" },
  { flag: "er", value: "Tigrinya" },
  { flag: "hk", value: "Traditional Chinese (Taiwan)" },
  { flag: "tr", value: "Turkish" },
  { flag: "ua", value: "Ukrainian" },
  { flag: "pk", value: "Urdu" },
  { flag: "uz", value: "Uzbek" },
  { flag: "vn", value: "Vietnamese" },
  { flag: "cy", value: "Welsh" },
  { flag: "za", value: "Xhosa" },
  { flag: "eu", value: "Yiddish" },
  { flag: "ng", value: "Yoruba" },
  { flag: "za", value: "Zulu" },
];
